name: Generate and Upload Doxygen

on:
  push:
    tags:
      - 'v*'

jobs:
  doxygen:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./laboratories/cicd-documentation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Doxygen
        run: sudo apt-get update && sudo apt-get install -y doxygen

      - name: Generate Documentation
        run: doxygen Doxyfile 

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: doxygen-documentation
          path: laboratories/cicd-documentation/html/